#!/bin/bash
# Сторож Charlotte v2.4 — тишина огня отличает поломку от сознательного отказа.
# v2.4 (27.08 22:30Z): (1) ветка 🟡 печатала КАЖДЫЕ 15 мин на неизменном состоянии —
#   три одинаковые побудки за 40 мин; теперь дедуп 60 мин, как у журнальной ветки.
# (2) порог «держится >6ч» был ВШИТЫМ ТЕКСТОМ, никто не считал длительность —
#   самоотчёт вместо режима. Теперь серия считается (S), 🔴 печатается ровно на 24-м
#   цикле подряд, и серия рвётся первой же пробой.
# (3) 💀 (поломка) НЕ дедупится никогда — негативный контроль на стенде.
# Стенды: 🟡 2 раза за 2ч вместо 8; 🔴 ровно 1 на 24-м; 💀 3 из 3; серия рвётся.
( while true; do ssh -o BatchMode=yes -o ConnectTimeout=15 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 root@185.173.146.134 "journalctl -u liquidator-bot -f --no-pager -o cat" 2>/dev/null | grep -E --line-buffered "SPECFIRE WIN|PlanExecuted|REFUSAL-LOSS|Traceback|CRITICAL|SamePoolInfeasible|§9 группа НЕ собрана|group_refused=[1-9]|transport_reject=[1-9]|fast-lane выключен|ЗАМОРОЖЕН|PREDICT МЁРТВ|kill-switch.*(СРАБОТ|LOSS|СТОП)|Main process exited|Started Liquidator|collect handler fail|арм НЕ ВЗВЁЛСЯ|несобираема|HR bid|выход сломан|RCPT-SHADOW РАСХОЖДЕНИЕ|перехват детонатора ОТКЛОНЁН|доска armed" | grep -vE "книжка выручки" | awk '{ cls=""; if ($0 ~ /Traceback/) cls="tb"; else if ($0 ~ /§9 группа НЕ собрана/) cls="g9"; else if ($0 ~ /collect handler fail/) cls="chf"; else if ($0 ~ /арм НЕ ВЗВЁЛСЯ/) cls="arm"; else if ($0 ~ /несобираема/) cls="ub"; else if ($0 ~ /ЗАМОРОЖЕН/) cls="idx"; else if ($0 ~ /перехват детонатора ОТКЛОНЁН/) cls="det"; else if ($0 ~ /доска armed/) cls="armed"; if (cls != "") { c=systime(); if (c-t[cls]<3600) { n[cls]++; next } t[cls]=c; n[cls]++; print $0 " [дедуп 60мин, счёт " cls ": " n[cls] "]"; fflush(); next } print; fflush() }'; echo "WATCHDOG: ssh-хвост журнала Charlotte оборвался, реконнект через 30с"; sleep 30; done ) & ( S=0; LAST=0; while true; do sleep 900; R=$(ssh -o BatchMode=yes -o ConnectTimeout=15 root@185.173.146.134 "L=\$(journalctl -u liquidator-bot --since '-30min' --no-pager -o cat 2>/dev/null); echo \"\$(echo \"\$L\" | grep -cE 'probe #|volley leg=') \$(echo \"\$L\" | grep -c 'shadow arm') \$(echo \"\$L\" | grep -c 'перехват детонатора ОТКЛОНЁН') \$(echo \"\$L\" | grep -c 'доска armed') \$(echo \"\$L\" | grep -oE 'dist [0-9.]+%' | sort -t' ' -k2 -n | head -1)\"" 2>/dev/null); set -- $R; P=${1:-}; A=${2:-0}; D=${3:-0}; ARMED=${4:-0}; NEAR="${5:-} ${6:-}"; NOW=$(date +%s); if [ -n "$P" ] && [ "$P" -eq 0 ] && [ "$A" -gt 0 ]; then if [ "$D" -gt 0 ]; then S=$((S+1)); M=$((S*15)); if [ $((NOW-LAST)) -ge 3600 ]; then echo "🟡 тишина ОБЪЯСНЕНА: проб=0, $D отказов по полу досягаемости (ближайшая цель $NEAR) — доска цела, достижимых целей нет. Держится ~${M}мин из 360 до порога; человеку делать нечего [дедуп 60мин]"; LAST=$NOW; fi; if [ "$S" -eq 24 ]; then echo "🔴 ПОРОГ ПРОБИТ: объяснённая тишина держится 6ч подряд (24 цикла по 15мин, серия НЕ прерывалась пробой). По правилу самой тревоги это значит, что направление «список кандидатов» НЕ РАБОТАЕТ. Ближайшая цель $NEAR"; fi; else S=0; echo "💀 ТИШИНА ОГНЯ БЕЗ ПРИЧИНЫ: за 30 мин проб=0 при армах=$A, армленных досок=$ARMED, отказов по полу=0 — это ПОЛОМКА, а не сознательный отказ (инцидент 27.08 08:14-13:29)"; fi; else S=0; fi; done ) & wait